name: 'KPI-action'
description: 'Action that generates Markdown reports for Key Performance Indicators (KPIs)'
author: 'AB Consulting & Technologies'
inputs:
  repo-token: # change this
    required: true
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}
  output-directory:
    description: 'The path for the markdown outputs'
    default: './Management'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
